### ISSUE TITLE
Usermode program not doing anything

### ISSUE THREAD

**Issue by HeroofHell** [alxbrn/rccom-leak#1]
I built the r6 project completely without problems and mapped the Driver with kdmapper, but when I start the client "Rise.exe" nothing happens when I press f1 although it at least should print something in the console right? Thanks in advance for any help.

**Comment by ALEHACKsp** [comment]
it works in 1809 build windows

**Comment by JayneFrack** [comment]
Hi I have the same problem but I am in windows 1809
