### ISSUE TITLE
Cheat Not doing anything

### ISSUE THREAD

**Issue by JayneFrack** [alxbrn/rccom-leak#3]
Sorry for asking again but my last thread was closed without an answer and I still have this problem. Could the problem be that the thread is created through "freopen("conin$", "r", stdin);" but there is no file named conin$ is that the problem? I would appreciate help. Thanks for leaking this :D

**Comment by JayneFrack** [comment]
I am guessing that there is a hwid check somewhere but I can't find it

**Comment by JayneFrack** [comment]
And I currently also have a problem loading the driver kdmapper only loads its vulnerable driver but the entry of the cheat driver is never actually called

**Comment by alxbrn** [comment]
This is a leak, if you want to use it then you need to figure it out yourself.

**Comment by MrSleekZ** [comment]
rip
